pipeline {
    agent any

  environment {
        DOCKERHUB_CREDENTIALS=credentials('dockerhub-token')
    }
  stages {
    stage('Git checkout') {
      steps {
        git credentialsId: 'git_credentials', url: 'https://github.com/yogeshk04/projects.git'
      }
    }
    stage('Package') {
      steps {
        sh '''cd XYZ_Technologies/
            mvn clean package
            mv target/*.war target/xyztech.war
        '''
      }
    }
    stage('Docker Build and Tag') {
      steps {
        sh '''cd XYZ_Technologies/
            sudo docker build -t xyztech:latest .
            sudo docker tag xyztech yogeshk04/xyztech:latest
        '''
      }
    }
    stage('DockerHub Login') {
      steps {
        sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
      }
    }
    stage('Publish image to Docker Hub') {
      steps {        
          sh 'sudo docker push yogeshk04/xyztech:latest'        
      }
    }

    stage('Run Docker container on Jenkins Agent') {
      steps {
        sh "docker run -d -p 8003:8080 yogeshk04/xyztech"
      }
    }
  }
}