---
# Source: abctechapp/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "abctech-service"  
  labels:
    helm.sh/chart: abctechapp-0.1.0
    app.kubernetes.io/name: abctechapp
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
  - name: http
    port: 8082
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: abctechapp
    app.kubernetes.io/instance: test
---
# Source: abctechapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  labels:
    helm.sh/chart: abctechapp-0.1.0
    app.kubernetes.io/name: abctechapp
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: abctechapp
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: abctechapp
        app.kubernetes.io/instance: test
    spec:
      containers:
      - name: abctechapp
        image: "yogeshk04/abctechapp"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
