pipeline {
    agent any

    environment {
        PATH = '/opt/maven:$PATH'
    }

    stages {

        stage('Clone') {
            steps {
                git credentialsId: 'git_credentials', url: 'https://github.com/yogeshk04/projects.git'
            }
        }

        stage('Build') {
            steps {
                withMaven(maven : 'maven_3_6_3')
                sh 'mvn clean install'
            }
        }

        stage('Test') {
            steps {
                withMaven(maven : 'maven_3_6_3')
                sh 'mvn test'
            }
        }
    
        stage('Deploy') {
            steps {
                echo 'Deploy Application'
            }
        }
    }
    
    post
    {
        always
        {
            emailext body: 'Pipeline summary', subject: 'ABC_Tech Pipleline status', to: 'yogeshk04@gmail.com'
        }
    }
}
