pipeline {
    agent any
    
    stages {
        stage('Git checkout') {
            steps {
                git credentialsId: 'git_credentials', url: 'https://github.com/yogeshk04/projects.git'
            }
        }
        stage('Build') {
            steps {
                sh '''cd ABC_Technologies/
                    mvn clean package
                    mv target/*.war target/abctech.war
                '''
            }
        }
        stage('Test') {
            steps {
                sh '''cd ABC_Technologies/
                    mvn test
                '''
            }
        }
        stage('Deploy') {
            steps {
                sh ''' cd ABC_Technologies/
                    sudo cp target/*.war /opt/tomcat/webapps/
                '''
            }
        }
    }
    
    post
    {
        always
        {
            //emailext body: 'Pipeline summary', subject: 'ABC_Tech Pipleline status', to: 'yoarsde@gmail.com'
            echo ('Email sent')
        }
    }
}
