pipeline {
    agent any

    stages {
        stage('git-clone') {
            steps {
                git credentialsId: 'git_credentials', 'https://github.com/yogeshk04/projects.git'
            }
        }
        stage('build') {
            steps {
                mvn clean install
            }
        }
        stage('Test') {
            steps {
                echo 'Test Application'
            }
        }
    
        stage('Deploy') {
            steps {
                echo 'Deploy Application'
            }
        }
    }
    
    post
    {
        always
        {
            emailext body: 'Pipeline summary', subject: 'ABC_Tech Pipleline status', to: 'yogeshk04@gmail.com'
        }
    }
}
